POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "ContentElements/Textteaser",
  "partial": "",
  "section": "",
  "arguments": {
    "data": {
      "external_media_source": "https://www.youtube.com/watch?v=ufcPzP1baPk",
      "teaser": "teaser",
      "bodytext": "[ContentElements/Textcolumn/Bodytext]\n Lorem ipsum doloret lipsum amtet dolores pagina morum est\n\n\n[/end]"
    }
  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
