POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "ContentElements/MenuCardList",
  "partial": "ContentElements/",
  "section": "Main",
  "arguments": {
    "data": {
      "pi_flexform": {
        "columns": "3"
      }
    },
    "settings": {
      "header": {
        "defaultHeaderType": 0
      },

      "gallery": {
        "columns": {
          "3": {
            "multiplier": {
            },
            "gutters": {},
            "corrections": {}
          }
        }
      }
    },
    "records": {
      "0": {
        "image": {
          "link": "http://www.de",
          "header": "record/image/header"
        }
      },
      "1": {
        "link": "http://www.de",
        "header": "record/image/header",
        "image": {
          "link": "http://www.de",
          "header": "record/image/header"
        }
      }
    }
  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
