POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "",
  "partial": "ContentElements/Media/Gallery",
  "section": "",
  "arguments": {

    "data": {
      "imagecols": 3
    },
    "settings": {
      "gallery": {
        "columns": {
          "3": {
            "multiplier": {

            },
            "gutters": {},
            "corrections": {}
          }
        }
      }
    },

    "files": {
      "0": {
          "properties": {
            "link": "http://www.de",
            "title": "Image Title",
            "src": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",
            "id": "591"
          }
      },
      "1": {
        "properties": {
          "link": "http://www.de",
          "title": "Image Title",
          "src": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",
          "id": "591"
        }
      }

    },

    "variants": {
      "xlarge" : {
        "src": "/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",
        "treatIdAsReference": false,
        "absolute": false,
        "width": "531",
        "minWidth": "530",
        "minHeight": "220",
        "height": "240",
        "fileExtension": "png"
      },
      "default": {
        "cropVariant": "default",
        "src": "/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",
        "treatIdAsReference": false,
        "absolute": false,

        "width": "534",
        "minWidth": "530",
        "minHeight": "220",
        "height": "240",
        "fileExtension": "jpg"
      }
    }

  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
