POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "",
  "partial": "ContentElements/Header/All",
  "section": "",
  "arguments": {
    "header": "Header",
    "layout": "0",
    "data": {
      "header_layout": 1,
      "header_position": "above",
      "header_link": "http://www.de",
      "header": "Header/All",
      "subheader": "Header/All/Subheader",
      "date": "2024-03-27",
      "layout": 1,
      "bodytext": "Primary bodytext, layout 0"
    },
    "settings": {
      "header": {
        "defaultHeaderType": 0,
        "layout": 1
      },
      "subheader": {
        "class": "subheader-class",
        "layout": 1
      }
    }
  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
