POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "ContentElements/Panel",
  "partial": "ContentElements/",
  "section": "Main",
  "arguments": {
    "debug": "true",
    "data": {
      "header": "Panel HTTP Header",
      "header_layout": "default",
      "bodytext": "Panel HTTP Bodytext"
    },
    "settings": {
      "header":{
        "defaultHeaderType": 3
      }
    }
  }
}

