POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "ContentElements/Carousel",
  "partial": "ContentElements/",
  "section": "Main",
  "arguments": {
    "data": {
      "uid": "0",
      "pi_flexform": {
        "transition": "fade",
        "interval": "100",
        "wrap": "true"
      }
    },
    "settings": {
      "header": {
        "defaultHeaderType": 0
      }
    },
    "records": {
      "0": {
        "uid": "0",
        "header": "carousel/record/0/header",
        "layout": "",
        "item_type": "",
        "data": {
            "item_type": "Image",
            "background_color": "",
            "text_color": ""
        }
      },
      "1": {
        "uid": "1",
        "link": "http://www.de",
        "header": "carousel/record/1/header",
        "layout": "",
        "item_type": "",
        "data": {
          "item_type": "Image",
          "background_color": "",
          "text_color": ""
        }
      }
    }
  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
