POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "ContentElements/TextmediaLeft",
  "partial": "ContentElements/",
  "section": "Main",
  "arguments": {
    "data": {
      "teaser": "teaser",
      "bodytext": "[ContentElements/TextmediaLeft/Bodytext]\n Lorem ipsum doloret lipsum amtet dolores pagina morum est\n\n\n[/end]",
      "imagecols": "3"
    },
    "settings": {
      "header": {
        "defaultHeaderType": 0
      },
      "gallery": {
        "columns": {
          "3": {
            "multiplier": {

            },
            "gutters": {

            },
            "corrections": {

            }
          }
        }
      }
    },
    "files": {

      "0": {
        "properties": {
          "link": "http://www.de",
          "title": "Image Title",
          "src": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png"
        }
      },
      "1": {
        "properties": {
          "link": "http://www.de",
          "title": "Image Title 2",
          "src": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png"
        }
      },
      "2": {
        "properties": {
          "link": "http://www.de",
          "title": "[767] the-creative-exchange-373981-unsplash.jpg",
          "_src": "/fileadmin/pexels-rostislav-uzunov-10613973__1080p__2e10da7287.mp4",
          "id" : 782,
          "_type": "video"
        }
      }



    }
  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
