POST https://t3v11.ddev.site/api/typo3fluid
Content-Type: application/json

{
  "extension": "bootstrappackage",
  "template": "",
  "partial": "ContentElements/Media/Rendering/Image",
  "section": "",
  "arguments": {

    "src": {
      "file": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png"
    },

    "data": {
      "src": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",
      "file": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png"
    },
    "file": "https://t3v11.ddev.site/fileadmin/_processed_/2/e/csm_Antilocapra_americana_Pronghorn_9f7cfcfb72.png",


    "settings": {
      "minHeight": "240"

    }

  },
  "password": "superpassword"
}

<> 2024-03-03T072853.404.html
<> 2024-03-03T072748.404.html
<> 2024-03-02T191105.404.html
<> 2024-03-02T163132.404.html
<> 2024-03-02T162710.404.html
<> 2024-03-02T103008.500.html
<> 2024-03-02T102551.400.txt
<> 2024-03-02T102521.400.txt
