services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Faeb\StorybookBootstrapPackage\:
    resource: '../Classes/*/*'
    exclude: '../Classes/Domain/Model/*'

  Faeb\StorybookBootstrapPackage\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-site-configuration'
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent

#  Faeb\StorybookBootstrapPackage\ViewHelpers\QueryParameters\:
#    resource: '../Classes/*'
#    autowire: true
#    autoconfigure: true
#    public: true


#  Faeb\StorybookBootstrapPackage\Classes\Configuration\PacketHelper:
#    autowire: true
#    autoconfigure: true
#    public: true


#  Faeb\StorybookBootstrapPackage\TypoScript\:
#    resource: '../Classes/TypoScript/*'
#    public: true
