services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Faeb\SitePackage\:
    resource: '../Classes/*/*'
    exclude: '../Classes/Domain/Model/*'

  Faeb\SitePackage\TsConfig\Loader:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-site-configuration'
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent

#  Faeb\SitePackage\ViewHelpers\QueryParameters\:
#    resource: '../Classes/*'
#    autowire: true
#    autoconfigure: true
#    public: true


#  Faeb\SitePackage\Classes\Configuration\PacketHelper:
#    autowire: true
#    autoconfigure: true
#    public: true


#  Faeb\SitePackage\TypoScript\:
#    resource: '../Classes/TypoScript/*'
#    public: true
